I had two failing tests in village_function, which was part of cardtest1. 
